DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY2RAZWZnLmNvbSIsImV4cCI6MTc0Mzk1OTc4NiwidXNlcklkIjoxfQ.vVPNfhjJKN7yYZSYKDeZV7q0mKVcoPD59JcOmAAssaU