apiVersion: v1
kind: Service
metadata:
  name: rest-api-pod-service
spec:
  selector:
    app: rest-api-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30924
  type: NodePort
